/**
 * Copyright (c) 2022, Red Vector, Inc.
 * All rights reserved
 */

/**
 * Author: Diego Martinez
 */
export {
  default as appReducer,
  appSelector,
  toggleThemeMode,
  setUILoading,
} from './app.slice';

// TODO - Promise the prefix rules of the api calls.
export {
  default as userReducer,
  userSelector,
  retrieveUsers,
} from './user.slice';

export {
  default as scoresReducer,
  entityScoringSelector,
  barChartLabelsSelector,
  categoriesSelector,
  barChartDataSelector,
  retrieveScores,
  retrieveScoresCount,
  retrieveHistoricalDataForModelAndEntity,
  isScoringInitializedSelector,
  basisReportSelector,
  isScoringReportInitializedSelector,
  retrieveBasis,
  retrieveBasisCount,
  scoringPageInfoSelector,
  changeLimit,
  changePageNumber,
  changeDataSourceId,
  getCurrentPageInfoByPageNumber,
  getAllCursorsByPageNumber,
  isScoringStatusPending,
  isScoringStatusFailed,
  isScoringStatusSuccess,
  getIsHistoricalDataInitialized,
} from './scoring.slice';

export {
  default as modelsReducer,
  retrieveModels,
  retrieveModel,
  saveModel,
  modifyModel,
  modelsSelector,
  getActiveModels,
  modelByIdSelector,
  modelNameByIdSelctor,
  modelIdsToNamesSelector,
  getModelListSelector,
  isModelsInitialized,
  modelAttributeIdsSelector,
  modelAttributesByIdSelector,
  modelAttributesSelector,
  newModelAttributesSelector,
  modelCategoriesByIdSelector,
  newModelCategoriesSelector,
  addNewModel,
  modelValueChangeHandler,
  setSelectedModelId,
  newModelRiskIndicatorTypesSelector,
  newModelSelector,
  newRiskIndicatorModelListById,
  newRiskIndicatorModelList,
  selectInitialAttribute,
  getSelectedModelId,
  modelsTreeSelector,
  modelTreeByIdSelector,
  modelFullAttributesSelector,
  deleteModel,
} from './model.slice';

export {
  default as attributesReducer,
  retrieveAttributes,
  retrieveAttribute,
  saveAttribute,
  attributesSelector,
  newAttributeSelector,
  newAttributeDatasourceIdSelector,
  newAttributeDatasource2IdSelector,
  newAttributeRiskFieldIdSelector,
  newAttributeRiskField2IdSelector,
  newAttributeAttributeTypeSelector,
  attributeByIdSelector,
  dataSourceByAttributeIdSelector,
  dataSource2ByAttributeIdSelector,
  riskFieldByAttributeIdSelector,
  riskField2ByAttributeIdSelector,
  attributeTypeByAttributeIdSelector,
  attributeNameByIdSelector,
  riskValueChangeHandler,
  riskValueClickHandler,
  addNewRiskIndicator,
  getIsAttributesInitialized,
  getCurrentAttributeIdSelector,
  getAttributeDataSourceIdSelector,
  getCurrentAttributeDataSourceIdSelector,
  deleteAttribute,
} from './attributes.slice';

export {
  default as filtersReducer,
  retrieveFilters,
  retrieveFilter,
  saveFilter,
  addNewFilter,
  filtersSelector,
  currentFilterSelector,
  filterByIdSelector,
  getCurrentFilterIdSelector,
} from './filters.slice';

export {
  default as entitiesReducer,
  getEntities,
  getEntity,
  getUnmaskedEntity,
  queryEntities,
  getEntitiesSelector,
  entitiesByIdSelector,
  entityByIdSelector,
  hasEntitiesSelector,
  needsEntitiesSelector,
  entityPropertiesByIdSelector,
  convertEntityPropertiesToDashBoardTable,
  getEntitiesByIdWithMasking,
  convertEntitiesPropertiesToDashBoardTable,
  getEntityComments,
  getIsEntitiesInitialized,
  getCommentsForEntityId,
  getIsCommentsInitialized,
  getStatusForEntityId,
  getIsEntityStatusInitialized,
  isEntityStatusPending,
  isEntityStatusSuccess,
  isEntityStatusFailed,
  getHistoryByEntityId,
  formatHistoryByEntityid,
  timeLineViewForEntityId,
  getHistoricalDataForEntityId,
  getOutlierTableData,
  getOutlierChartData,
  getEntityStatus,
  getFrameStart,
} from './entity.slice';

export {
  default as statsReducer,
  getLatestStat,
  getStatsSelector,
  getStatsByModelIdSelector,
  getSelectedStats,
  statByModelIdSelector,
  statsToStatusCards,
  getStatsInitialized,
  deleteStats,
  isStatsStatusPending,
  isStatsStatusSuccess,
  isStatsStatusFailed,
  getAllStatsByDataSource,
  getStatsByDataSourceId,
  getFiltersByDataSourceId,
  getStatsByDataSourceIdAndFeatureName,
  getStatsByDataSourceIdFeatureAndFieldName,
} from './stat.slice';

export {
  default as configReducer,
  retrieveDataSources,
  retrieveEntitiesConfig,
  retrieveRiskIndicatorsConfig,
  getDataSourcesSelect,
  getDataSourcesFields,
  getDataSourcesConfigInitialized,
  getEntitiesConfigInitialized,
  getEntityProperties,
  getEntityDetailProperties,
  getEntityStatusValues,
  getEntityMaskingValues,
  getHomePageTopPercent,
  getRiskIndicatorsConfigInitialized,
  getNumberTopRiskIndicators,
} from './config.slice';

export {
  default as controlReducer,
  ingestData,
  replayData,
  resetModels,
  refreshModels,
  scoreModels,
} from './control.slice';

export {
  default as listsReducer,
  retrieveLists,
  retrieveList,
  newList,
  getListsInitialized,
  listsSelector,
  getNewList,
  getSelectedListById,
  getSelectedListNameById,
  addNewList,
  listValueChanger,
  setSelectedListId,
  getSelectedListId,
  getListIds,
  deleteList,
} from './list.slice';

export {
  default as graphReducer,
  retrieveGraphData,
  retrievePeerData,
  getGraphDataSelector,
  getPeerDataSelector,
  peerChartDataSelector,
  graphChartDataSelector,
} from './graph.slice';

export {
  default as externalReducer,
  retrieveExternalData,
  getExternalDataSelector,
  saveExternalData,
} from './external.slice';

export { default as riskReducer, downloadExcelFile } from './risk.slice';

export {
  default as governanceReducer,
  retrieveMaskingSystemStatus,
  setSystemMaskingStatus,
  retrieveMaskingSystemAutoUnmaskPercentage,
  setMaskingSystemAutoUnmaskPercentage,
  retrieveMaskingSystemAutoUnmaskTopCount,
  setMaskingSystemAutoUnmaskTopCount,
  retrieveMaskingSystemRemaskDays,
  setMaskingSystemRemaskDays,
  retrieveMaskings,
  retrieveMaskingsByStatus,
  retrieveMasking,
  setNewMasking,
  removeMasking,
  getAuditEvents,
  getEntityStatusEvents,
  isGovernanceSystemMaskingLoadingSelector,
  isGovernanceAutoUnmaskPercentLoadingSelector,
  isGovernanceAutoUnmaskTopCountLoadingSelector,
  isGovernanceRemaskAfterDaysLoadingSelector,
  isGovernanceEntitiestoMaskLoadingSelector,
  isGovernanceAuditEventsLoadingSelector,
  isGovernanceEntityStatusesLoadingSelector,
  isGovernanceSystemMaskingInitializedSelector,
  isGovernanceAutoUnmaskPercentInitializedSelector,
  isGovernanceAutoUnmaskTopCountInitializedSelector,
  isGovernanceRemaskAfterDaysInitializedSelector,
  isGovernanceEntitiestoMaskInitializedSelector,
  isGovernanceAuditEventsInitializedSelector,
  isGovernanceEntitiesStatusesInitializedSelector,
  isGovernanceSystemMaskingStatusPendingSelector,
  isGovernanceSystemMaskingStatusSuccessSelector,
  isGovernanceSystemMaskingStatusFailedSelector,
  isGovernanceAutoUnmaskPercentStatusPendingSelector,
  isGovernanceAutoUnmaskPercentStatusSuccessSelector,
  isGovernanceAutoUnmaskPercentStatusFailedSelector,
  isGovernanceAutoUnmaskTopCountStatusPendingSelector,
  isGovernanceAutoUnmaskTopCountStatusSuccessSelector,
  isGovernanceAutoUnmaskTopCountStatusFailedSelector,
  isGovernanceRemaskAfterDaysStatusPendingSelector,
  isGovernanceRemaskAfterDaysStatusSuccessSelector,
  isGovernanceRemaskAfterDaysStatusFailedSelector,
  isGovernanceEntitiestoMaskStatusPendingSelector,
  isGovernanceEntitiestoMaskStatusSuccessSelector,
  isGovernanceEntitiestoMaskStatusFailedSelector,
  isGovernanceAuditEventsStatusPendingSelector,
  isGovernanceAuditEventsStatusSuccessSelector,
  isGovernanceAuditEventsStatusFailedSelector,
  isGovernanceEntityStatusesStatusPendingSelector,
  isGovernanceEntityStatusesStatusSuccessSelector,
  isGovernanceEntityStatusesStatusFailedSelector,
  getSystemMaskingSelector,
  getAutoUnmaskPercentSelector,
  getAutoUnmaskTopCountSelector,
  getRemaskAfterDaysSelector,
  getEntitiesToMaskSelector,
  getMaskedEntitySelector,
  getMaskedEntityIdsSelector,
  getEntityStatusesEntityIdsSelector,
  getUnmaskedTableData,
  getAuditEventsSelector,
  getEntityStatusLog,
  getEntityStatusTableData,
} from './governance.slice';

export {
  default as notificationsReducer,
  retrieveNotification,
  retrieveNotifications,
  createNotification,
  removeNotification,
  retrieveNotificationEvent,
  retrieveNotificationEvents,
  createNotificationEvent,
  removeNotificationEvent,
  isNotificationsInitializedSelector,
  isNotificationEventsInitializedSelector,
  isNotificationsLoadingSelector,
  isNotificationEventsLoadingSelector,
  isNotificationsStatusPendingSelector,
  isNotificationsStatusSuccessSelector,
  isNotificationsStatusFailedSelector,
  isNotificationEventsStatusPendingSelector,
  isNotificationEventsStatusSuccessSelector,
  isNotificationEventsStatusFailedSelector,
  getNotifications,
  getNotificationById,
  getNotificationEvents,
  getNotificationEventsForNotificationId,
  getNotificationEventObjectForNotificationId,
  getNotificationEventsForNotificationIdAndEntityId,
  getNotificationEventObjectForNotificationIdAndEntityId,
  getNotificationEventForNotificationIdEntityIdAndScoringInstance,
  getNotificationsForTable,
  getNotificationEventsForTable,
  getNotificationEventsEntityIds,
  getNotificationEventsCount,
} from './notification.slice';

export {
  default as reportReducer,
  retrieveRiskStatusSummary,
  retrieveStatusOverTime,
  retrievePersonsPer,
  retrieveProgramsData,
  retrieveRiskScoreSummary,
  retrieveIndividualsRiskIndicator,
  retrieveOrganizationData,
  riskStatusSummarySelector,
  statusOverTimeSelector,
  personPerSelector,
  programListSelector,
  riskScoreSummarySelector,
  individualsRiskIndicatorSelector,
  organizationListSelector,
} from './report.slice';
